services:

  dev:
    image: anime-site
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: anime-site
    command: sleep infinity
    environment: 
      - MONGODB_CONNSTRING=mongodb://developer:developer@mongodb
    volumes:
      - projects:/projects
    ports:
      - "${BACKEND_PORT:-8000}:8000"
      - "${FRONTEND_PORT:-3000}:3000"

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=developer
      - MONGO_INITDB_ROOT_PASSWORD=developer
    volumes:
      - mongodb:/var/lib/mysql
    ports:
      - "${FORWARD_DB_PORT:-27017}:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${FORWARD_MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: developer
      ME_CONFIG_MONGODB_ADMINPASSWORD: developer
      ME_CONFIG_MONGODB_URL: mongodb://developer:developer@mongodb:27017/

volumes:
  projects:
  mongodb: